### ISSUE TITLE
Reduction/Concatenation operations are not supported

### ISSUE THREAD

**Issue by ilkerkesen** [JuliaGPU/GPUArrays.jl#28]
Vector reduction (sum(A,1), maximum(A,(2,3)) etc.) and concatenation operations are not supported currently and I think its error message is not informative as much as possible. It just points out indexing is not supported; but this has nothing to with indexing.

Thanks.

**Comment by SimonDanisch** [comment]
Solved by #37

**Comment by ilkerkesen** [comment]
I think GPUArrays still doesn't support array->vector, array->array reduction. Example code snippet:

```julia
using GPUArrays
CUBackend.init()

a1 = rand(4,5); g1 = GPUArray(a1)
sum(g1,1)

a2 = rand(3,4,5); g2 = GPUArray(a2)
sum(g2,1)
```

[CuArrays](https://github.com/MikeInnes/CuArrays.jl) has support for all kinds of reductions. Maybe they can be ported to GPUArrays also.

**Comment by SimonDanisch** [comment]
ah, i think they're actually ported from here with the addition of the dimension ;)

**Comment by SimonDanisch** [comment]
Btw, do you actually plan to use Float64 instead of Float32?

**Comment by ilkerkesen** [comment]
No, I don't have any particular interest to use Float64 instead of Float32.
